version: '3.8'
services:
  merch-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - kafka
      - migrator
    env_file:
      - .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

migrator:
  image: migrate/migrate:v4.18.1
  volumes:
    - ./migrations:/migrations
  command:
    - "-path=/migrations"
    - "-database=postgres://postgres:postgres@postgres:5432/merch?sslmode=disable"
    - "up"
  depends_on:
    - postgres

volumes:
  postgres_data: